apiVersion: v1
kind: Namespace
metadata:
  name: kube-events-maker
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-events-maker
  name: kube-events-maker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-events-maker-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-events-maker-role
subjects:
  - kind: ServiceAccount
    namespace: kube-events-maker
    name: kube-events-maker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-events-maker-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
