apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-events-maker
  namespace: kube-events-maker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-events-maker
        version: v1-alpha
    spec:
      serviceAccountName: kube-events-maker
      containers:
        - name: kube-events-maker
          image: hegaoyuan/kube-events-maker:latest
          imagePullPolicy: Always
          args:
            - -conf=/data/config.yaml
          volumeMounts:
            - mountPath: /data
              name: cfg
      volumes:
        - name: cfg
          configMap:
            name: kube-events-maker-cfg
  selector:
    matchLabels:
      app: kube-events-maker
      version: v1-alpha
